# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc85a5d8c6f8bbc0c5aee5a563359df404818713a702f81fb37b60608cd31e7b41f32e19ad165f15116f03beede44f54a157132d90d5eef01c84cbb0c67f270d

test:
  secret_key_base: 06bda4d3172045793dc7ef29c485a753ff27df6ae33822bd6a08bf93973ffca512e1d11aa321999af516d879d4fe06eca3da37e6e180f138aae351194509a407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
